export const FETCH_HEROES = 'FETCH_HEROES'
export const FETCH_HEROES_FAILURE = 'FETCH_HEROES_FAILURE'
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS'

export default {
  FETCH_HEROES,
  FETCH_HEROES_FAILURE,
  FETCH_HEROES_SUCCESS
}
